#!/bin/sh
set -e

user=cardistryio

if [[ $(whoami) -eq "root" ]]; then
  echo <<-EOS
    This script requires that you're not logged in as root
    Create a new user with 'adduser $user'
  EOS
  exit 1
fi
